name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "Setting up environment..."
        echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV

    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman

    - name: Build container
      run: | 
        podman build -t devops-test-demo:${{ github.sha }} .

    - name: Start container
      run: |
        podman run -p 8081:80 --name test-container devops-test-demo:${{ github.sha }}
        #wait for container to start
        sleep 10
        for initialisation 
                podman ps | grep test-container || { echo "Container not running"; exit 1; }

    - name: Check container logs
      run: |
        podman logs test-container || true


    - name: Lint HTML
      run: |
        sudo npm install -g htmlhint

    - name: Check container security
      run: |
        # Basic security check of container
        podman inspect devops-test-demo:${{ github.sha }}


        
