name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "Setting up environment..."
        echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV

    - name: Build container
      run: | 
        podman build -t devops-test-demo:${{ github.sha }} .

    - name: Test container
      run: |
        podman run -d --name test-container -p 8081:80 devops-test-demo:${{ github.sha }}
        #wait for container to start
        sleep 5
        #Test if container is running
        podman ps | grep test-container

    - name: Lint HTML
      run: |
        sudo npm install -g htmlhint

    - name: Check container security
      run: |
        # Basic security check of container
        podman inspect devops-test-demo:${{ github.sha }}


        
